name: 自动更新 Cloudflare IP 地址池

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时执行一次

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ 检出仓库
        uses: actions/checkout@v3

      - name: 🧰 安装依赖
        run: sudo apt update && sudo apt install -y curl jq

      - name: 📥 执行收集脚本
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
        run: bash collect_ips.sh

      - name: 🛠️ 提交更新
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add ip-json/*.json 2>/dev/null || echo "⚠️ 没有匹配的文件"
          git commit -m "✅ 自动更新 IP 地址池 - $(date '+%Y-%m-%d %H:%M:%S')" || echo "✅ 没有需要提交的更改"

      - name: 🚀 推送更新
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://${GH_TOKEN}@github.com/${{ github.repository }}
          git push origin main
