name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Post Checkout Repository
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: 设置 Git 身份
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 运行 collect_ips.sh
        run: |
          chmod +x collect_ips.sh
          ./collect_ips.sh

      - name: 提交并推送更改
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add ip-json/*.json all_ips.txt 2>/dev/null || echo "⚠️ 没有匹配的文件"
          git commit -m "📦 Update IP JSON by Country" || echo "✅ 没有需要提交的更改"
          git push https://x-access-token:${GH_TOKEN}@github.com/Unc1e1u0-2030/ip.git HEAD:main || echo "❌ 推送失败，请检查 Token 权限"
