name: 🌐 自动采集 Cloudflare 优选 IP

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时执行一次
  workflow_dispatch:

jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 克隆仓库
        uses: actions/checkout@v3

      - name: 🛠️ 安装依赖
        run: sudo apt-get install -y curl

      - name: 📥 执行 IP 采集脚本
        run: bash collect_ips.sh
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}

      - name: 🧾 提交更新
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ip-json/*.json 2>/dev/null || echo "⚠️ 没有匹配的文件"
          git commit -m "✅ 自动更新优选 IP - $(date '+%F %T')" || echo "✅ 没有需要提交的更改"
          git push
