name: Auto Collect and Push IPs

on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时执行一次
  workflow_dispatch:  # 可手动触发

jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run collector
        run: |
          chmod +x collect_ips.sh
          ./collect_ips.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}

      - name: Commit and Push if changes
        run: |
          git add ip-json/*.json 2>/dev/null || echo "⚠️ 没有匹配的文件"
          git commit -m "🤖 自动更新 IP 列表 $(date +'%F %T')" || echo "✅ 没有需要提交的更改"
          git push https://github.com/${{ github.repository }}.git HEAD:main
