name: Auto Update IP DB

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Environment
        run: sudo apt update && sudo apt install -y nmap jq python3

      - name: Download Cloudflare IPs and Generate JSON
        run: |
          chmod +x collect_ips.sh
          ./collect_ips.sh

      - name: Commit and Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add ip-json/ result/
          git commit -m "🤖 Auto update country IP list"
          git push
