name: 自动更新 US IP 列表

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时执行一次

jobs:
  collect-us:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v3

      - name: 安装依赖
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: 执行 US IP 收集脚本
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
        run: |
          chmod +x collect_us_only.sh
          ./collect_us_only.sh

      - name: 提交并推送变更
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ip-json/US.json
          git commit -m "✅ 自动更新 US IP 列表 - $(date '+%Y-%m-%d %H:%M:%S')" || echo "⚠️ 没有变更需要提交"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
