name: Update IP JSON by Country

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 🧹 清理旧目录
        run: rm -rf ip && mkdir ip

      - name: 🌀 克隆仓库
        run: |
          git clone https://github.com/Unc1e1u0-2030/ip.git ip
          cd ip
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: 📥 执行收集脚本
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
        run: |
          chmod +x ./ip/collect_ips.sh
          ./ip/collect_ips.sh

      - name: 📦 提交更改
        run: |
          cd ip
          git add ip-json/*.json 2>/dev/null || echo "⚠️ 没有匹配的文件"
          git commit -m "✅ 自动更新 IP JSON $(date '+%Y-%m-%d %H:%M:%S')" || echo "✅ 没有需要提交的更改"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Unc1e1u0-2030/ip.git HEAD:main
